// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGQ5zEPmK45vmWBGIsl9y0rKJkXIE0d6g',
    appId: '1:40843384061:web:e59af4c8195b75ab0c1a94',
    messagingSenderId: '40843384061',
    projectId: 'todoapp-yeomnin',
    authDomain: 'todoapp-yeomnin.firebaseapp.com',
    storageBucket: 'todoapp-yeomnin.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClpp0YIZ1pf0XU9OSoZR__PWWljChfNgY',
    appId: '1:40843384061:android:193512152d2b89190c1a94',
    messagingSenderId: '40843384061',
    projectId: 'todoapp-yeomnin',
    storageBucket: 'todoapp-yeomnin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYud9wznbZeDJSZRgItwj8-cCphw75dvE',
    appId: '1:40843384061:ios:6129c1ca0eab27460c1a94',
    messagingSenderId: '40843384061',
    projectId: 'todoapp-yeomnin',
    storageBucket: 'todoapp-yeomnin.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYud9wznbZeDJSZRgItwj8-cCphw75dvE',
    appId: '1:40843384061:ios:6129c1ca0eab27460c1a94',
    messagingSenderId: '40843384061',
    projectId: 'todoapp-yeomnin',
    storageBucket: 'todoapp-yeomnin.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGQ5zEPmK45vmWBGIsl9y0rKJkXIE0d6g',
    appId: '1:40843384061:web:e76278b03ca5a5570c1a94',
    messagingSenderId: '40843384061',
    projectId: 'todoapp-yeomnin',
    authDomain: 'todoapp-yeomnin.firebaseapp.com',
    storageBucket: 'todoapp-yeomnin.firebasestorage.app',
  );
}
